# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Text generated from the settings table: --help=env, --help=features, man § ENVIRONMENT."""
from __future__ import annotations

from pathlib import Path

from brew_hop_search.settings import SETTINGS, Setting, env_name, config_key, SCOPES
from brew_hop_search.display import fmt_duration

_SCOPE_TITLE = {"hop": "every brew-hop tool", "search": "brew-hop-search", "peek": "brew-hop-peek"}


def fmt_default(s: Setting) -> str:
    d = s.default
    if d is None:
        return "(none)"
    if s.kind == "bool":
        return "on" if d else "off"
    if s.kind == "duration":
        return fmt_duration(int(d), sub_minute=True)
    if s.kind == "list":
        return "[" + ",".join(d) + "]"
    if s.kind == "path":
        p = Path(d)
        try:
            return "~/" + str(p.relative_to(Path.home()))
        except ValueError:
            return str(p)
    return str(d)


def _rows(scope: str) -> list[Setting]:
    return [s for s in SETTINGS if s.scope == scope]


def render_env_help(tool: str = "search") -> str:
    out = [
        "  settings",
        "",
        "    flag > tool env > family env > config [tool] > config [hop] > default",
        "    Every BREW_HOP… name has a HOMEBREW_HOP… twin: brew filters the",
        "    environment to HOMEBREW_* before running `brew hop`, so use the twin there.",
        "",
    ]
    for scope in SCOPES:
        rows = _rows(scope)
        if not rows:
            continue
        out.append(f"  [{scope}]  {_SCOPE_TITLE[scope]}")
        width = max(len(env_name(s, scope)) for s in rows)
        for s in rows:
            name = env_name(s, scope).ljust(width)
            cfg = "" if s.env_only else f"  {config_key(s, scope)}"
            out.append(f"    {name}  {s.kind:<8} {fmt_default(s):<14}{cfg}")
            out.append(f"    {'':{width}}  {s.doc}")
        out.append("")
    out.append("  override for one tool: BREW_HOP_SEARCH_<KEY> / BREW_HOP_PEEK_<KEY>, or [search] / [peek] in config")
    return "\n".join(out) + "\n"


def render_features_help(tool: str = "search") -> str:
    from brew_hop_search.features import KNOWN_FEATURES, features_enabled, unknown_features
    on = features_enabled(tool)
    out = ["  features  (experimental; off by default; outside the 1.0 promise)", ""]
    width = max(len(n) for n in KNOWN_FEATURES)
    for name, doc in KNOWN_FEATURES.items():
        state = "on " if name in on else "off"
        out.append(f"    {name.ljust(width)}  {state}  {doc}")
    unk = unknown_features(tool)
    if unk:
        out += ["", f"    enabled but unknown (ignored): {', '.join(unk)}"]
    out += ["",
            "    enable:  BREW_HOP_FEATURES=peek,clock   (comma list)",
            "             BREW_HOP_FEATURE_PEEK=1         (one per feature)",
            "             [hop] features = [\"peek\"]      (config.toml)",
            "             under `brew hop`: HOMEBREW_HOP_FEATURES=…"]
    return "\n".join(out) + "\n"


MAN_BEGIN = "<!-- settings:begin (generated by scripts/gen-man-env.py; do not edit) -->"
MAN_END = "<!-- settings:end -->"


def _shown(s: Setting, value) -> str:
    if s.kind == "secret":
        return "set"
    if s.kind == "bool":
        return "on" if value else "off"
    if s.kind == "duration":
        return fmt_duration(int(value), sub_minute=True)
    if s.kind == "list":
        return ",".join(value)
    return str(value)


def non_defaults(tool: str = "search") -> list[tuple[str, str, str]]:
    """(name-in-own-scope, shown value, source) for every setting not at default."""
    from brew_hop_search.settings import resolve
    rows = []
    for s in SETTINGS:
        r = resolve(s.key, tool)
        if r.source == "default":
            continue
        rows.append((env_name(s, s.scope), _shown(s, r.value), r.source))
    return rows


def notes(tool: str = "search") -> list[str]:
    """Every resolver note (twin conflicts, ignored garbage), deduplicated."""
    from brew_hop_search.settings import resolve
    seen: list[str] = []
    for s in SETTINGS:
        for n in resolve(s.key, tool).notes:
            if n not in seen:
                seen.append(n)
    return seen


def render_man_environment() -> str:
    """Markdown for the man page's ENVIRONMENT section, between the generated markers."""
    out = ["Every `BREW_HOP…` name below has a `HOMEBREW_HOP…` twin; `brew hop` only",
           "passes `HOMEBREW_*` through, so set the twin when running under brew.",
           "Precedence: flag > tool env > family env > config `[tool]` > config `[hop]` > default.",
           ""]
    for scope in SCOPES:
        rows = _rows(scope)
        if not rows:
            continue
        out.append(f"### [{scope}] — {_SCOPE_TITLE[scope]}")
        out.append("")
        for s in rows:
            cfg = "" if s.env_only else f" (config: `{config_key(s, scope)}`)"
            out.append(f"* `{env_name(s, scope)}`:")
            out.append(f"  {s.doc}. Default `{fmt_default(s)}`{cfg}.")
            out.append("")
    return "\n".join(out).rstrip() + "\n"
